# Generated by Django 2.2.3 on 2019-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_like_count'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='post.Post'),
        ),
    ]
