# Generated by Django 2.2.1 on 2019-05-25 10:27

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
